name: Push from RepoC/main to RepoD/main

on:
  push:
    branches:
      - main

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código de la rama 'main' del repositorio RepoC
    - name: Checkout RepoC main branch
      uses: actions/checkout@v2
      with:
        ref: main

    # Paso 2: Configurar Git
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    # Paso 3: Clonar el repositorio MAIN y la rama 'DEV'
    - name: Clone main repository main branch
      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
      run: |
        git clone --branch main https://x-access-token:${TARGET_REPO_TOKEN}@github.com/your-username/MAIN_PROYFIAFIT.git target-repo

    # Paso 4: Sincronizar los cambios de la rama 'main' del repositorio FRONT a la rama 'DEV' del repositorio MAIN
    - name: Sync changes to main/main branch
      run: |
        rsync -av --exclude='.git' ./ target-repo/
        cd target-repo
        git add .
        git commit -m "Auto-sync from RepoC/main"
        git push origin main
